dist: trusty
language: python
services:
  - docker
before_install:
  - docker-compose up -d
sudo: false
python:
  - "3.8.0"
cache:
  directories:
    - $HOME/.env/pip
script:
  - python --version
  - pip install pyleniumio
  - python -m pytest ui_tests/test_qap_dev_docker.py --remote_url="http://localhost:4444/wd/hub"