dist: trusty

language: python         # this works for Linux but is an error on macOS or Windows
python: 3
install: pip3 install --upgrade pip
script:
  - python3 --version
  - pip3 install virtualenv
  - virtualenv .env
  - source .env/bin/activate
  - pip install pyleniumio
  - pip freeze
  - python3 -m pytest ui_tests/test_qap_dev.py