language: python
python:
    - "3"
  cache:
    directories:
      - $HOME/.env/pip
script:
  - python3 --version
  - pip3 install virtualenv
  - virtualenv .env
  - source .env/bin/activate
  - pip install pyleniumio
  - pip freeze
  - python3 -m pytest ui_tests/test_qap_dev.py