dist: trusty
language: python
python:
    - "3.6"
services:
  - docker
script:
  - python --version
  - pip install pyleniumio
  - docker-compose up -d
  - sleep 20
  - python -m pytest ui_tests/test_qap_dev_docker.py --remote_url="http://localhost:4444/wd/hub"