dist: trusty
language: python
python:
    - "3.6"
services:
  - docker
before_install:
  - docker pull selenium/node-firefox:3.8.1-francium
  - docker pull selenium/hub:3.8.1-francium
  - docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.8.1-francium
  - docker run -d --link selenium-hub:hub --name selenium-node-firefox -v /dev/shm:/dev/shm selenium/node-firefox:3.8.1-francium
script:
  - python --version
  - pip3 install pyleniumio
  - sleep 5
  - python -m pytest ui_tests/test_qap_dev_docker.py --remote_url="http://localhost:4444/wd/hub"