language: python
sudo: false
python:
  - "3.8.0"
cache:
  directories:
    - $HOME/.env/pip
script:
  - python3 --version
  - pip3 install virtualenv
  - virtualenv .env
  - source .env/bin/activate
  - pip3 install pyleniumio
  - pip3 freeze
  - python3 -m pytest ui_tests/test_qap_dev.py